name: demo-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run : echo "Hello World!"
      - name: Checkout code
        uses: actions/checkout@v3  # Récupère le code source du dépôt

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Utilise Python 3.9

      - name: Install dependencies
        run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

  lint:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - name: Lint with flake 8
         run : pip install flake8

  test:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v3
      - name: Test
        run : |
              pip install nose
              nose tests



